#ifndef BTM_TD_ENUMS_H
#define BTM_TD_ENUMS_H

#include "jdksmidi_incl.h"

namespace btm_td{
	namespace music{
		namespace enums{

			namespace TDMsgType{
				enum TDMsgType {
					NOTE = jdksmidi::NOTE_ON,
					META = jdksmidi::META_EVENT,
					SYSEX = jdksmidi::SYSEX_START_A,
					PEDAL = jdksmidi::C_SOFT_PEDAL,
					UNKNOWN = 255
				};
				enum TDMetaMsgType{
					TEMPO = jdksmidi::META_TEMPO,
					TIMESIG = jdksmidi::META_TIMESIG,
					KEYSIG = jdksmidi::META_KEYSIG,
					EOT = jdksmidi::META_END_OF_TRACK,
					META_UNKNOWN = 255
				};
			}

			namespace MIDIMsgType{
				enum MIDIMsgType {
					NOTE_ON = jdksmidi::NOTE_ON,
					NOTE_OFF = jdksmidi::NOTE_OFF,
					NOTE_AFTERTOUCH = jdksmidi::POLY_PRESSURE,
					CONTROL_CHANGE = jdksmidi::CONTROL_CHANGE,
					PROGRAM_CHANGE = jdksmidi::PROGRAM_CHANGE,
					CHANNEL_AFTERTOUCH = jdksmidi::CHANNEL_PRESSURE,
					PITCH_BEND = jdksmidi::PITCH_BEND,
					META = jdksmidi::META_EVENT
				};
			}

			namespace MIDIControlChangeMsgType {
				enum MIDIControlChangeMsgType{
					BANK_SELECT = jdksmidi::C_GM_BANK,
					MODULATION = jdksmidi::C_MODULATION,
					BREATH_CONTROLLER = jdksmidi::C_BREATH,
					FOOT_CONTROLLER = jdksmidi::C_FOOT,
					PORTAMENTO_TIME = jdksmidi::C_PORTA_TIME,
					DATA_ENTRY = jdksmidi::C_DATA_ENTRY,
					MAIN_VOLUME = jdksmidi::C_MAIN_VOLUME,
					BALANCE = jdksmidi::C_BALANCE,
					PAN = jdksmidi::C_PAN,
					EXPRESSION_CONTROLLER = jdksmidi::C_EXPRESSION,
					EFFECT_CONTROL_1 = 0x0C,
					EFFECT_CONTROL_2 = 0x0D,
					GENERAL_CONTROLLER_1 = jdksmidi::C_GENERAL_1,
					GENERAL_CONTROLLER_2 = jdksmidi::C_GENERAL_2,
					GENERAL_CONTROLLER_3 = jdksmidi::C_GENERAL_3,
					GENERAL_CONTROLLER_4 = jdksmidi::C_GENERAL_4,
					LSB_FOR_CONTROLLER_1 = jdksmidi::C_LSB,
					DAMPER_PEDAL = jdksmidi::C_DAMPER,
					PORTAMENTO = jdksmidi::C_PORTA,
					SOSTUNENTO = jdksmidi::C_SOSTENUTO,
					SOFT_PEDAL = jdksmidi::C_SOFT_PEDAL,
					LEGATO_FOOT = 0x44,
					HOLD_2 = jdksmidi::C_HOLD_2,
					SOUND_CONTROLLER_1 = 0x46,
					GENERAL_CONTROLLER_5 = jdksmidi::C_GENERAL_5,
					GENERAL_CONTROLLER_6 = jdksmidi::C_GENERAL_6,
					GENERAL_CONTROLLER_7 = jdksmidi::C_GENERAL_7,
					GENERAL_CONTROLLER_8 = jdksmidi::C_GENERAL_8,
					PORTAMENTO_CONTROL = 0x54,
					EFFECTS_DEPTH_1 = jdksmidi::C_EFFECT_DEPTH,
					DATA_INCREMENT = jdksmidi::C_DATA_INC,
					DATA_DECREMENT = jdksmidi::C_DATA_DEC,
					NON_REG_PARAM_LSB = jdksmidi::C_NONRPN_LSB,
					NON_REG_PARAM_MSB = jdksmidi::C_NONRPN_MSB,
					REG_PARAM_LSB = jdksmidi::C_RPN_LSB,
					REG_PARAM_MSB = jdksmidi::C_RPN_MSB,
					MODE_MSG = 0x79,
					ALL_SOUNDS_OFF = jdksmidi::C_ALL_SOUNDS_OFF,
					RESET = jdksmidi::C_RESET,
					LOCAL_CONTROL = jdksmidi::C_LOCAL,
					ALL_NOTES_OFF = jdksmidi::C_ALL_NOTES_OFF,
					OMNI_OFF = jdksmidi::C_OMNI_OFF,
					OMNI_ON = jdksmidi::C_OMNI_ON,
					POLY_ON = 0x7E,
					POLY_OFF = 0x7F,
				};
			}

			namespace  MIDIMetaMsgType {
				enum MIDIMetaMsgType {
					SEQUENCE_NO = jdksmidi::META_SEQUENCE_NUMBER,
					TEXT_EVENT = jdksmidi::META_GENERIC_TEXT,
					TEXT_COPYRIGHT = jdksmidi::META_COPYRIGHT,
					TEXT_TRACK_NAME = jdksmidi::META_TRACK_NAME,
					TEXT_INSTRUMENT_NAME = jdksmidi::META_INSTRUMENT_NAME,
					TEXT_LYRICS = jdksmidi::META_LYRIC_TEXT,
					TEXT_MARKER = jdksmidi::META_MARKER_TEXT,
					TEXT_CUE_POINT = jdksmidi::META_CUE_POINT,
					TEXT_CHANNEL_PREFIX = jdksmidi::META_CHANNEL_PREFIX,
					END_OF_TRACK = jdksmidi::META_END_OF_TRACK,
					TEMPO = jdksmidi::META_TEMPO,
					SMPTE_OFFSET = jdksmidi::META_SMPTE,
					TIME_SIG = jdksmidi::META_TIMESIG,
					KEY_SIG = jdksmidi::META_KEYSIG,
					SEQUENCER_SPECIFIC = jdksmidi::META_SEQUENCER_SPECIFIC
				};
			}

			namespace MIDIInstrument {
				enum MIDIInstrument {
					ACOUSTIC_GRAND_PIANO = 0,
					BRIGHT_ACOUSTIC_PIANO = 1,
					ELECTRIC_GRAND_PIANO = 2,
					HONKY_TONK_PIANO = 3,
					ELECTRIC_PIANO_1_RHODES_PIANO = 4,
					ELECTRIC_PIANO_2_CHORUSED_PIANO = 5,
					HARPSICHORD = 6,
					CLAVINET = 7,
					CELESTA = 8,
					GLOCKENSPIEL = 9,
					MUSIC_BOX = 10,
					VIBRAPHONE = 11,
					MARIMBA = 12,
					XYLOPHONE = 13,
					TUBULAR_BELLS = 14,
					DULCIMER_SANTUR = 15,
					DRAWBAR_ORGAN_HAMMOND = 16,
					PERCUSSIVE_ORGAN = 17,
					ROCK_ORGAN = 18,
					CHURCH_ORGAN = 19,
					REED_ORGAN = 20,
					ACCORDION_FRENCH = 21,
					HARMONICA = 22,
					TANGO_ACCORDION_BAND_NEON = 23,
					ACOUSTIC_GUITAR_NYLON = 24,
					ACOUSTIC_GUITAR_STEEL = 25,
					ELECTRIC_GUITAR_JAZZ = 26,
					ELECTRIC_GUITAR_CLEAN = 27,
					ELECTRIC_GUITAR_MUTED = 28,
					OVERDRIVEN_GUITAR = 29,
					DISTORTION_GUITAR = 30,
					GUITAR_HARMONICS = 31,
					ACOUSTIC_BASS = 32,
					ELECTRIC_BASS_FINGERED = 33,
					ELECTRIC_BASS_PICKED = 34,
					FRETLESS_BASS = 35,
					SLAP_BASS_1 = 36,
					SLAP_BASS_2 = 37,
					SYNTH_BASS_1 = 38,
					SYNTH_BASS_2 = 39,
					VIOLIN = 40,
					VIOLA = 41,
					CELLO = 42,
					CONTRABASS = 43,
					TREMOLO_STRINGS = 44,
					PIZZICATO_STRINGS = 45,
					ORCHESTRAL_HARP = 46,
					TIMPANI = 47,
					STRING_ENSEMBLE_1_STRINGS = 48,
					STRING_ENSEMBLE_2_SLOW_STRINGS = 59,
					SYNTHSTRINGS_1 = 50,
					SYNTHSTRINGS_2 = 51,
					CHOIR_AAHS = 52,
					VOICE_OOHS = 53,
					SYNTH_VOICE = 54,
					ORCHESTRA_HIT = 55,
					TRUMPET = 56,
					TROMBONE = 57,
					TUBA = 58,
					MUTED_TRUMPET = 69,
					FRENCH_HORN = 60,
					BRASS_SECTION = 61,
					SYNTHBRASS_1 = 62,
					SYNTHBRASS_2 = 63,
					SOPRANO_SAX = 64,
					ALTO_SAX = 65,
					TENOR_SAX = 66,
					BARITONE_SAX = 67,
					OBOE = 68,
					ENGLISH_HORN = 69,
					BASSOON = 70,
					CLARINET = 71,
					PICCOLO = 72,
					FLUTE = 73,
					RECORDER = 74,
					PAN_FLUTE = 75,
					BLOWN_BOTTLE = 76,
					SHAKUHACHI = 77,
					WHISTLE = 78,
					OCARINA = 79,
					LEAD_1_SQUARE_WAVE = 80,
					LEAD_2_SAWTOOTH_WAVE = 81,
					LEAD_3_CALLIOPE = 82,
					LEAD_4_CHIFFER = 83,
					LEAD_5_CHARANG = 84,
					LEAD_6_VOICE_SOLO = 85,
					LEAD_7_FIFTHS = 86,
					LEAD_8_BASS_LEAD = 87,
					PAD_1_NEW_AGE_FANTASIA = 88,
					PAD_2_WARM = 89,
					PAD_3_POLYSYNTH = 90,
					PAD_4_CHOIR_SPACE_VOICE = 91,
					PAD_5_BOWED_GLASS = 92,
					PAD_6_METALLIC_PRO = 93,
					PAD_7_HALO = 94,
					PAD_8_SWEEP = 95,
					FX_1_RAIN = 96,
					FX_2_SOUNDTRACK = 97,
					FX_3_CRYSTAL = 98,
					FX_4_ATMOSPHERE = 99,
					FX_5_BRIGHTNESS = 100,
					FX_6_GOBLINS = 101,
					FX_7_ECHOES_DROPS = 102,
					FX_8_SCI_FI_STAR_THEM = 103,
					SITAR = 104,
					BANJO = 105,
					SHAMISEN = 106,
					KOTO = 107,
					KALIMBA = 108,
					BAG_PIPE = 109,
					FIDDLE = 110,
					SHANAI = 111,
					TINKLE_BELL = 112,
					AGOGO = 113,
					STEEL_DRUMS = 114,
					WOODBLOCK = 115,
					TAIKO_DRUM = 116,
					MELODIC_TOM = 117,
					SYNTH_DRUM = 118,
					REVERSE_CYMBAL = 119,
					GUITAR_FRET_NOISE = 120,
					BREATH_NOISE = 121,
					SEASHORE = 122,
					BIRD_TWEET = 123,
					TELEPHONE_RING = 124,
					HELICOPTER = 125,
					APPLAUSE = 126,
					GUNSHOT = 127
				};
			}

			namespace MIDIInstrument10 {
				enum MIDIInstrument10 {
					ACOUSTIC_BASS_DRUM = 35,
					BASS_DRUM_1 = 36,
					SIDE_STICK = 37,
					ACOUSTIC_SNARE = 38,
					HAND_CLAP = 39,
					ELECTRIC_SNARE = 40,
					LOW_FLOOR_TOM = 41,
					CLOSED_HI_HAT = 42,
					HIGH_FLOOR_TOM = 43,
					PEDAL_HI_HAT = 44,
					LOW_TOM = 45,
					OPEN_HI_HAT = 46,
					LOW_MID_TOM = 47,
					HI_MID_TOM = 48,
					CRASH_CYMBAL_1 = 49,
					HIGH_TOM = 50,
					RIDE_CYMBAL_1 = 51,
					CHINESE_CYMBAL = 52,
					RIDE_BELL = 53,
					TAMBOURINE = 54,
					SPLASH_CYMBAL = 55,
					COWBELL = 56,
					CRASH_CYMBAL_2 = 57,
					VIBRASLAP = 58,
					RIDE_CYMBAL_2 = 59,
					HI_BONGO = 60,
					LOW_BONGO = 61,
					MUTE_HI_CONGA = 62,
					OPEN_HI_CONGA = 63,
					LOW_CONGA = 64,
					HIGH_TIMBALE = 65,
					LOW_TIMBALE = 66,
					HIGH_AGOGO = 67,
					LOW_AGOGO = 68,
					CABASA = 69,
					MARACAS = 70,
					SHORT_WHISTLE = 71,
					LONG_WHISTLE = 72,
					SHORT_GUIRO = 73,
					LONG_GUIRO = 74,
					CLAVES = 75,
					HI_WOOD_BLOCK = 76,
					LOW_WOOD_BLOCK = 77,
					MUTE_CUICA = 78,
					OPEN_CUICA = 79,
					MUTE_TRIANGLE = 80,
					OPEN_TRIANGLE = 81
				};
			}
		}
	}

}
#endif